name = "gwzz-link-gate"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "LINKS_KV"
id = "fd11232d686540fdbd52aa1c0c0b95fe"

[vars]
ADMIN_TOKEN = "df716c7817eddbb862a329c1e75c11ff336a3bca5574eae2"
SITE_DOMAIN = "gwzz.xyz"
